openapi: 3.2.0
info:
  contact:
    email: support@equinixmetal.com
    name: Equinix Metal API Team
  description: '# Introduction

    Equinix Metal provides a RESTful HTTP API which can be reached at .'
  license:
    name: Equinix Metal
    url: https://metal.equinix.com/legal/
  termsOfService: https://metal.equinix.com/legal/
  title: Metal Usages API
  version: 1.0.0
servers:
- url: https://api.equinix.com/metal/v1
security:
- x_auth_token: []
tags:
- description: Usage Management
  externalDocs:
    url: https://metal.equinix.com/developers/docs/billing/checking-usage/
  name: Usages
paths:
  /devices/{id}/usages:
    get:
      description: Returns all usages for a device.
      operationId: findDeviceUsages
      parameters:
      - description: Device UUID
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
      - description: Filter usages created after this date
        in: query
        name: created[after]
        schema:
          format: datetime
          type: string
      - description: Filter usages created before this date
        in: query
        name: created[before]
        schema:
          format: datetime
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceUsageList'
          description: ok
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: unauthorized
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: not found
      summary: Retrieve all usages for device
      tags:
      - Usages
  /projects/{id}/usages:
    get:
      description: Returns all usages for a project.
      operationId: findProjectUsage
      parameters:
      - description: Project UUID
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
      - description: Filter usages created after this date
        in: query
        name: created[after]
        schema:
          format: datetime
          type: string
      - description: Filter usages created before this date
        in: query
        name: created[before]
        schema:
          format: datetime
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectUsageList'
          description: ok
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: unauthorized
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: not found
      summary: Retrieve all usages for project
      tags:
      - Usages
components:
  schemas:
    Error:
      description: Error responses are included with 4xx and 5xx HTTP responses from the API service. Either "error" or "errors" will be set.
      properties:
        error:
          description: A description of the error that caused the request to fail.
          type: string
        errors:
          description: A list of errors that contributed to the request failing.
          items:
            description: An error message that contributed to the request failing.
            type: string
          type: array
      type: object
    ProjectUsage:
      example:
        total: total
        unit: unit
        quantity: quantity
        plan_version: plan_version
        price: price
        name: name
        type: type
        facility: facility
        plan: plan
      properties:
        facility:
          type: string
        name:
          type: string
        plan:
          type: string
        plan_version:
          type: string
        price:
          type: string
        quantity:
          type: string
        total:
          type: string
        type:
          type: string
        unit:
          type: string
      type: object
    ProjectUsageList:
      example:
        usages:
        - total: total
          unit: unit
          quantity: quantity
          plan_version: plan_version
          price: price
          name: name
          type: type
          facility: facility
          plan: plan
        - total: total
          unit: unit
          quantity: quantity
          plan_version: plan_version
          price: price
          name: name
          type: type
          facility: facility
          plan: plan
      properties:
        usages:
          items:
            $ref: '#/components/schemas/ProjectUsage'
          type: array
      type: object
    DeviceUsageList:
      example:
        usages:
        - total: total
          unit: unit
          quantity: quantity
        - total: total
          unit: unit
          quantity: quantity
      properties:
        usages:
          items:
            $ref: '#/components/schemas/DeviceUsage'
          type: array
      type: object
    DeviceUsage:
      example:
        total: total
        unit: unit
        quantity: quantity
      properties:
        quantity:
          type: string
        total:
          type: string
        unit:
          type: string
      type: object
  securitySchemes:
    x_auth_token:
      description: 'HTTP header containing the User or Project API key that will be used to authenticate the request.

        '
      in: header
      name: X-Auth-Token
      type: apiKey
      x-displayName: X-Auth-Token
x-tagGroups:
- name: Accounts and Organization
  tags:
  - Authentication
  - Emails
  - Invitations
  - Memberships
  - Organizations
  - OTPs
  - PasswordResetTokens
  - PaymentMethods
  - Projects
  - SSHKeys
  - SupportRequest
  - TransferRequests
  - TwoFactorAuth
  - Users
  - UserVerificationTokens
- name: Services and Billing
  tags:
  - Events
  - Facilities
  - Incidents
  - Invoices
  - Licenses
  - Metros
  - Plans
  - Usages
- name: Servers
  tags:
  - Devices
  - Batches
  - Capacity
  - HardwareReservations
  - OperatingSystems
  - Ports
  - SelfServiceReservations
  - SpotMarket
  - Userdata
  - Volumes
- name: Networking
  tags:
  - BGP
  - Interconnections
  - IPAddresses
  - MetalGateways
  - VLANs
  - VRFs
